version: '3.7'

services:
  mariadb:
    image: mariadb:10.8.3
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=laravel

  app:
    build: ./docker/app
    environment:
      - TZ=Asia/Taipei
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=laravel
    volumes:
      - ./src:/var/www
      - ./docker/app/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/app/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - mariadb

  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - '8080:80'
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params
